name: Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          ARTICLES_PER_TAG_PAGE: 1000
          NEXT_PUBLIC_MEILISEARCH_URL: ${{ vars.NEXT_PUBLIC_MEILISEARCH_URL }}
          NEXT_PUBLIC_MEILISEARCH_KEY: ${{ vars.NEXT_PUBLIC_MEILISEARCH_KEY }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
